### PR TITLE
Fixed bad SQL query

### PR DESCRIPTION
**Pull request by fcapovilla**
Tried to improve the play/0 query for issue #150.

### CODE REVIEW

**Comment by bglusman** [comment]
Hey Man!  Thanks for looking at this!  If I'm reading correctly (haven't tried locally yet) you took a different approach than I was trying to in the linked elixirforum post!  The SQL there only pulls foods that are stocked at the facility over the wire, if I'm reading this correct this will still pull all foods over the wire, but fewer fields from them via the select fields?  That's not a bad idea, I think it's a more incremental improvement than I was trying for, but doesn't hurt, and maybe I'm wrong?  Did you read over the post there?  Maybe we can remote pair on this at some point, or something else, but I can still merge this in either way if you want to get credit for hacktoberfest before worrying about what's next :-)  The play function isn't actually used though, it should really be deleted, its just the pure SQL/ecto part of the actual food selection query immediately above it.

**Comment by fcapovilla** [comment]
Since I don't have a lot of data in my database, I don't know how exactly how this query will behave with real data.
In my tests, the query seemed to only return foods for existing stocks, since the query starts at the stocks table and goes through the other tables with left joins.

I've set up my dev environment using the s3 method. I'll try to use the docker method and see if I can test the query with more data that way.

**Comment by fcapovilla** [comment]
Also, I've already done my 4 pull requests for Hacktoberfest, so merging this pull requests isn't really necessary.

**Comment by bglusman** [comment]
Awesome!  I'll also pull down the PR and play with locally when I have a chance.... though I'm confused, if you used s3 dump method I'd think you'd have a ton of data?  It's mainly the factory method that gives very little, I think?  But either way, really appreciate the repeat performance, excited to have another collaborator on board!

**Comment by bglusman** [comment]
Awesome stuff, maybe we'll both learn something about Ecto here!

**Comment by fcapovilla** [comment]
Also : The previous query did 5 SQL queries in order to get all its data. The new query only does a single query. I'm guessing this will help too. :)

**Comment by fcapovilla** [comment]
Ok, after checking my database, it seems I have around 8789 rows in my foods table, so I guess I have enough data?
The new query only fetches the data it needs in a single SQL query, so it doesn't have to send unnecessary food data over the wire : 
```
[debug] QUERY OK source="stocks" db=5.1ms
SELECT s0."id", f1."longdesc", f1."manufacturer_name", f2."foodgroup_desc", c3."name" FROM "stocks" AS s0 INNER JOIN "foods" AS f1 ON f1."ndb_no" = s0."food_id" INNER JOIN "foods" AS f4 ON f4."ndb_no" = s0."food_id" INNER JOIN "food_groups" AS f2 ON f2."foodgroup_code" = f4."foodgroup_code" INNER JOIN "credit_type_memberships" AS c5 ON c5."food_group_id" = f2."foodgroup_code" INNER JOIN "credit_types" AS c3 ON c5."credit_type_id" = c3."id" WHERE (s0."arrival" < $1) AND (s0."expiration" > $2) AND ($3 = s0."facility_id") ORDER BY c3."name" [{2017, 10, 14}, {2017, 10, 14}, 1]
```
The previous query did multiple SQL query, some of them returning a lot of unnecessary data : 
```
[debug] QUERY OK source="credit_types" db=18.0ms decode=4.3ms
SELECT c0."id", c0."name", c0."credits_per_period", c0."period_name", c0."inserted_at", c0."updated_at" FROM "credit_types" AS c0 INNER JOIN "credit_type_memberships" AS c4 ON c4."credit_type_id" = c0."id" INNER JOIN "food_groups" AS f3 ON c4."food_group_id" = f3."foodgroup_code" INNER JOIN "foods" AS f2 ON f2."foodgroup_code" = f3."foodgroup_code" INNER JOIN "stocks" AS s1 ON s1."food_id" = f2."ndb_no" WHERE (s1."arrival" < $1) AND (s1."expiration" > $2) AND ($3 = s1."facility_id") ORDER BY c0."name" [{2017, 10, 14}, {2017, 10, 14}, 1]
[debug] QUERY OK source="food_groups" db=2.9ms
SELECT f0."foodgroup_code", f0."foodgroup_desc", c1."id" FROM "food_groups" AS f0 INNER JOIN "credit_types" AS c1 ON c1."id" = ANY($1) INNER JOIN "credit_type_memberships" AS c2 ON c2."credit_type_id" = c1."id" WHERE (c2."food_group_id" = f0."foodgroup_code") ORDER BY c1."id" [[1, 2]]
[debug] QUERY OK source="foods" db=16.5ms decode=8.9ms
SELECT f0."ndb_no", f0."longdesc", f0."manufacturer_name", f0."foodgroup_code", f0."foodgroup_code" FROM "foods" AS f0 WHERE (f0."foodgroup_code" = ANY($1)) ORDER BY f0."foodgroup_code" [["1100", "1200", "1600", "1800", "1900", "2000", "2500"]]
[debug] QUERY OK source="stocks" db=11.5ms
SELECT s0."id", s0."quantity", s0."override_text", s0."arrival", s0."expiration", s0."packaging", s0."credits_per_package", s0."weight", s0."storage", s0."image", s0."max_per_person", s0."max_per_package", s0."food_id", s0."meal_id", s0."offer_id", s0."facility_id", s0."inserted_at", s0."updated_at", s0."food_id" FROM "stocks" AS s0 WHERE (s0."food_id" = ANY($1)) ORDER BY s0."food_id" [["11380", "11384", "11385", "11386", "11387", "11390", "11391", "11392", "11393", "11394", "11395", "11396", "11397", "11398", "11399", "11400", "11401", "11402", "11403", "11614", "11406", "11407", "11408", "11409", "11411", "11412", "11413", "11414", "11416", "11417", "11418", "11419", "11422", "11423", "11424", "11426", "11427", "11428", "11429", "11430", "11431", "11432", "11435", "11436", "11437", "11438", "11439", "11442", "11444", "11445", ...]]
[debug] QUERY OK source="foods" db=1.6ms
SELECT f0."ndb_no", f0."longdesc", f0."manufacturer_name", f0."foodgroup_code", f0."ndb_no" FROM "foods" AS f0 WHERE (f0."ndb_no" = ANY($1)) [["11001", "11282", "20545"]]
[debug] QUERY OK source="food_groups" db=1.2ms
SELECT f0."foodgroup_code", f0."foodgroup_desc", f0."foodgroup_code" FROM "food_groups" AS f0 WHERE (f0."foodgroup_code" = ANY($1)) [["1100", "2000"]]

```
My guess is that using "select:" instead of "preload:" made all the difference, because this way we tell Ecto exactly what we need, so it doesn't need to fetch all the data of intermediary tables "just in case".

Also, starting from the filtered table (stocks) instead of the credit_types table seems to also have an effect on the number of SQL queries done by Ecto. After some tests, I guess the direction of the relations has something to do with it (belongs_to vs has_many).

**Comment by fcapovilla** [comment]
Oh! I think I've found why the first query did 5 SQL queries : 
The preload starts at credit_types. So, in order to preload everything, Ecto goes this way : 
credit_types -> food_groups -> foods -> stocks -> foods -> food_groups

Starting at stocks does only 3 SQL queries with preloads. Using selects takes that down to 1.

**Comment by bglusman** [comment]
Oh this sounds awesome!  Fee free to move it over to the main query above and delete play method but either way l'll verufyater and merge this in!  Thanks man, killing it!

**Comment by bglusman** [comment]
(ironic because I THOUGHT the old query was doing only one query and I'd worked hard to make it one query, but just thought because of the joins it had to pull over everything somehow because... Well some of it is discussed in linked forum discussion but either way if page still functions once this is replaced in above query and contents look the same then it works for me!)

**Comment by fcapovilla** [comment]
I'm looking at the main query, and I see that the preloads might be necessary in this case because the data is then sent to the templates.
I'll try to find a way to adapt my query for this situation, but it won't be easy.

**Comment by fcapovilla** [comment]
I pushed a first try at optimizing the stock_by_type function.
The query seems faster, but I don't get exactly the same results as the previous query.
I wonder if it has something to do with the direction of the query (From stocks to credit_types).
I'm looking into it.

**Comment by fcapovilla** [comment]
The only difference I noticed is that the food item "Alfalfa seeds, sprouted, raw" doesn't appear with my version of the query.
After looking into it, the stock for this food item is expired (expiration == 2017-03-01), so I think this item wasn't supposed to be visible and this was a bug in the old query.

Can you test this new version on your side?
Thank you.

**Comment by bglusman** [comment]
Awesome!  Sounds totally possible, thanks again!

**Comment by bglusman** [comment]
@fcapovilla just tested and works great!  There was an earlier version of this that started from stocks but had its own problem, I forget details, but interesting how this seems to effect Ecto's interpretation/behavior.  In any case, thank's so much man, going to merge in now!  I'm also going to give you commit access, and would love to invite you to be a maintainer on the project going forward if you're interested!  Have been hoping to expand the pool of people interested in this a bit, and really appreciate your help!  Look forward to talking more soon!

**Comment by fcapovilla** [comment]
Thank you!
I'm interested in participating in your project, and I'll try to work on issues when I have some free time.

**Pull request merged**
