### PR TITLE
Add requirement for GUARDIAN_SECRET_KEY environment variable

### PR DESCRIPTION
**Pull request by cheerfulstoic**
Very small PR.  This change doesn't let you start the app if the `GUARDIAN_SECRET_KEY` environment variable isn't set.

The `mix.exs` seemed like the place to do it because it's part of the base Elixir app, but I'm happy to put it somewhere else too.

### CODE REVIEW

**Comment by bglusman** [comment]
There's actually an open issue for this #168, but I think we'd much rather just give it a default value in dev/and use an env var in production or something, there's really no need to control it in a dev environment...  thanks for looking at this though!  It's really easy I just keep forgetting to do it when thinking of it/at a computer I can test it on locally... plus might remove the thing in docker-compose.yml that handles there since wouldn't be needed anymore.

**Comment by cheerfulstoic** [comment]
Wouldn't setting a default value be a security risk?  If you forget to set it on some new environment and it sets it silently then it's set to a known value

**Comment by bglusman** [comment]
It's not a default globally it would be done in Co fig/dev.exs I think, so only dev default... I meant to do this weekend but got lazy/distracted 🙃

**Comment by cheerfulstoic** [comment]
Ah, fair enough.  Though in production I could still imagine it being confusing if somebody was setting up the app and forgot to set the value and it gave the error which I got (which wasn't clear at all).  Maybe that's fine if the app will only ever be in one place, or maybe it's fine because you're not worried about forgetting about this issue after all of this discussion (assuming that you'll only ever be the one setting it up).  I've just tripped over my own feet enough times that I try to leave breadcrumbs for myself and others ;)

**Comment by bglusman** [comment]
Sure could combine with this for that use case/concern

**Comment by bglusman** [comment]
@cheerfulstoic I think this is a pretty good way to go.. top of mix.exs isn't actually a useful place to put for your use case of prevenitng production issues, as mix isn't typically a part of production environments, but this makes sure it's configured somehow.

**Comment by cheerfulstoic** [comment]
:+1: Cool, I didn't really know where to put it since I'm not very familiar with the Elixir / Phoenix boot process yet.  The `OpenPantry` application module seems ideal, though, thanks!

Is this good to go?  Should I make this my first PR merge? ;)

**Comment by bglusman** [comment]
Yeah, go for it!

**Pull request merged**
