### PR TITLE
Add an "Empty cart" button.

### PR DESCRIPTION
**Pull request by fcapovilla**
Fix for issue #105.

### CODE REVIEW

**Comment by fcapovilla** [comment]
Went the easy way by removing everything in Javascript.

The harder but more efficient way would have been to clear everything server-side in a single transaction using Ecto.Multi, but it seemed a little too complex with all the quantity recalculations for all food types.
A new issue could be opened to try this method for future optimizations.

**Comment by bglusman** [comment]
I suspect along with your other PR this will be good, but may merge in that one first, and/or play with whether I have an idea how to do this atomically... will also be good to play with and this is probably fine, but the potential flood of separate updates in both directions from this makes me a tiny bit nervous.

**Review by bglusman — COMMENTED** [review]
Pending verification/possible alternative may be OK

**Comment by bglusman** [comment]
I kind of want to hold off on this as just not that important for now/problematic in approach, so I'm going to close for now, @komizutama if this is feature is really important we can re-open or re-prioritize, but its less easy than it sounded because of the reasons discussed above and this feels like hack to me for now.

**Comment by fcapovilla** [comment]
I understand. I might give this issue another try once I'm done with other higher priority tickets. :)

**Comment by bglusman** [comment]
Yeah, I don't think this is that big a deal, but if it is I bet there's a refactor to be done with the current Ecto.multi to just not commit the multi but take a and return a multi, and the current behavior calls that with an empty/new multi and the new behavior goes through entire cart reducing a new multi through that function for everything in the cart.

**Pull request closed without merging**
