### PR TITLE
Kill PostGIS dependency

### PR DESCRIPTION
**Pull request by bglusman**
@komizutama @net Finally killing the stupid PostGIS requirement/usage, not totally sure though about the details since we want new people to never have needed it, but existing people to be able to migrate forward to lose it...  So appreciate a quick eye @net since this bit you, and will notify Jason offline as I don't know his github....

### CODE REVIEW

**Comment by cheerfulstoic** [comment]
Trying to set up the app and getting an error when it tries to remove `postgis` other things depend on it.  Thoughts?

```
03:48:51.657 [info]  == Running OpenPantry.Repo.Migrations.RemoveGeoColumnFromFacility.change/0 forward

03:48:51.657 [info]  alter table facilities

03:48:51.712 [info]  execute "DROP EXTENSION IF EXISTS postgis"
** (Postgrex.Error) ERROR 2BP01 (dependent_objects_still_exist): cannot drop extension postgis because other objects depend on it

extension postgis_topology depends on extension postgis
extension postgis_tiger_geocoder depends on extension postgis
    (ecto) lib/ecto/adapters/sql.ex:195: Ecto.Adapters.SQL.query!/5
    (ecto) lib/ecto/adapters/postgres.ex:86: anonymous fn/4 in Ecto.Adapters.Postgres.execute_ddl/3
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/adapters/postgres.ex:86: Ecto.Adapters.Postgres.execute_ddl/3
    (ecto) lib/ecto/migration/runner.ex:98: anonymous fn/2 in Ecto.Migration.Runner.flush/0
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/migration/runner.ex:96: Ecto.Migration.Runner.flush/0
    (stdlib) timer.erl:181: :timer.tc/2
    (ecto) lib/ecto/migration/runner.ex:27: Ecto.Migration.Runner.run/6
    (ecto) lib/ecto/migrator.ex:127: Ecto.Migrator.attempt/6
    (ecto) lib/ecto/migrator.ex:73: anonymous fn/4 in Ecto.Migrator.do_up/4
    (ecto) lib/ecto/adapters/sql.ex:620: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
    (db_connection) lib/db_connection.ex:1275: DBConnection.transaction_run/4
    (db_connection) lib/db_connection.ex:1199: DBConnection.run_begin/3
    (db_connection) lib/db_connection.ex:790: DBConnection.transaction/3
    (ecto) lib/ecto/migrator.ex:250: anonymous fn/4 in Ecto.Migrator.migrate/4
    (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
    (ecto) lib/mix/tasks/ecto.migrate.ex:84: anonymous fn/4 in Mix.Tasks.Ecto.Migrate.run/2
    (elixir) lib/enum.ex:645: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:645: Enum.each/2
```

**Comment by bglusman** [comment]
Huh, that's weird... we tested this I think since it was removed..  @net tested it and had to add the 2e8e66d commit to make it work IIRC.  can try commenting out that migration and see if that fixes I guess?  Not totally sure what to say, ideally we can get a PR to fix this as the old migrations adding it were removed for exactly this reason so it wouldn't be needed but could be removed if anyone had added...

**Comment by cheerfulstoic** [comment]
Interesting, I commented out the line in the migration and it went through fine.  I'll see where I can get ;). One thing that I noticed is that the `Dockerfile` uses the `mdillon/postgis` image for the DB, so maybe the `Dockerfile` hasn't been updated since this PR?

**Comment by bglusman** [comment]
Oh!  I wonder if you are using postgis for other things in your database and the extension is needed for you?

**Comment by bglusman** [comment]
Cause on a clean database pretty sure it works but if you HAVE the postgis extension NOT because of openpantry (which used to add it), it would still remove it here, "if exists", but if you have it and other things rely on it, then it errors?  that makes sense to me anyway but just a theory.  Dunno if there's a fix for that other than deleting that migration from the codebase now that it was never/should never be added for people in the first place.

**Comment by cheerfulstoic** [comment]
I don't think so.  I set up openpantry with docker so it's a separate postgres database from the one that I had on my system (which I actually shut down anyway).  So it should just have the openpantry DB in it.  But maybe the `docker-compose.yml` needs to be updated to not use `mdillon/postgis` but rather some general `postgres` image?

**Comment by bglusman** [comment]
Oh right, good call... We probably never tasted this on docker I forgot... Yeah probably regular Postgres image is all that's needed in docker-compose.yml

**Pull request merged**
