### PR TITLE
Add a button to remove an item from the cart directly + replace inline SVGs with img tags.

### PR DESCRIPTION
**Pull request by fcapovilla**
Fix for issue #118 .

### CODE REVIEW

**Comment by fcapovilla** [comment]
A new commit was added to this pull request to fix issue #106.

**Comment by bglusman** [comment]
@fcapovilla so I pulled this down to poke locally, since our integration tests haven't been good for spotting anything but egregious breaks in functionality since the CSS refactor months ago (this is why I have the headless chrome branch up, phantomjs just doesn't support flexbox properly, but I didn't get wallaby chrome working on travis yet).  At first glance this all works, but second glance... no so much :-)  It seems like now I can add one item to cart, and clear the cart, but adding a second item doesn't work... there's also a weird two click problem where first add-to-cart click changes to text, and second click changes to the +/= quantity selection.

It looks like the first 3 commits were fine, and both of these problems are introduced by the last commit to fix the SVG's, so we could seperate this up, merge in the working part and figure out the SVG fix seperately, or maybe some combo of you, me and @komizutama can figure out the SVG issue..  @komizutama also has a branch that may be changing things a bunch more which is part of why I've held off on working more to fix the tests until that's done, as they want a more card based stock management UI rather than row based.  Either way, I expect the SVG stuff in here is a good start!  If you're interested I can also give you access to our staging heroku server for playing around, but really we just need to fix up the integration tests to be less worthless, I haven't tried to fix the chrome branch in over a month or two, so probably time to poke at that again so it'll be easier to get @komizutama 's branch tested before we merge it in rather than after :-)

**Comment by fcapovilla** [comment]
Oh! I only tested the changes on Firefox and everything worked there, but I can reproduce the problems you mentioned in Chrome.
I'll see if I can fix the problems.

**Comment by bglusman** [comment]
Also in case it conflicts with your work can also look at @komizutama 's branch here https://github.com/openpantry/open_pantry/compare/color_tabs_cards and hopefully avoid unnecessary conflicts etc, though may be inevitable... I haven't played with it locally and not sure how close it is

**Comment by fcapovilla** [comment]
I did some refactoring to the Javascript code in order to make it work in Firefox and Chrome.
Sadly, it will totally conflict with the color_tabs_cards branch...

If you want, I can separate my two fixes into different pull requests so the SVG fix can be merged later.

**Comment by bglusman** [comment]
@fcapovilla thanks, and sorry about the conflict!  It occurred to me after I suggested dealing with SVG stuff since touching it, maybe will be easier to get your branch in first and @komizutama and I will rebase theirs on yours, dunno...  also, could go this route https://github.com/smooth-code/svgr , as we've been kind of wanting to try out some react in the app/@komizutama already has some experience, dunno... I'm using react/redux at work now and it might give me extra time to justify working on OP if it's a tech playground for tech to use at work, like absinthe-graphql.org which I super want to use :-)  Specifically interested in subscriptions in absinthe, though none of that effects the SVG's much, but...  we'll see :-)  Thanks again, and let us know any thoughts for how we can organize better to keep and attract more amazing people like yourself to help maintain and grow the project!

**Review by bglusman — APPROVED** [review]
This seems fixed now, thanks!  DIscovered a totally unrelated bug while verifying, but it's present on master also, and I kind of know the gist of where it must come from, though no clean repro yet, but probably not hard to reproduce.  Opened a new issue, will merge this pending coordination with @komizutama

**Comment by komizutama** [comment]
This all looks good to me. I am totally fine with merging you in first and then rebasing on top of it. I did a test merge without commit locally and it worked out pretty well/I didn't see any glaring bugs/blockers. So,  I'm gonna go ahead and merge it to master.Thank you @fcapovilla!

**Pull request merged**
